### ISSUE TITLE
Feature request: Use WalletConnect's Web3Modal to handle wallet connection in clientAnonymousVoting

### ISSUE THREAD

**Issue by adityabhattad2021** [AOSSIE-Org/Agora-Blockchain#29]
Why?
- Using custom register logic is quite cumbersome. We have to handle all the logic ourselves, from detecting Ethereum to handling cases when the user's browser doesn't have a wallet present. Additionally, if the user wants to connect with a different wallet other than MetaMask, Web3Modal handles it all by itself.
- The `useWeb3ModalAccount` hook provided by Web3Modal proves to be useful in multiple places in the codebase. It allows us to avoid writing code to fetch the address from the browser wallet. The hook helps us easily manage the address globally throughout the application, resulting in less error-prone and cleaner code.

**Comment by 12sachingupta** [comment]
These are the limitations of the Web3Modal

Vendor Lock-in: 
By tightly integrating with Web3Modal, you may find yourself locked into its ecosystem. If you later decide to switch to a different wallet integration solution or implement custom logic, you may face challenges migrating away from Web3Modal.

Documentation and Support: 
While Web3Modal provides documentation and community support, the level of assistance may not be as extensive as official Ethereum or Web3.js documentation. Depending on your team's expertise and the complexity of your requirements, you may encounter difficulties troubleshooting issues or finding solutions to advanced problems.
