### ISSUE TITLE
Make the artifacts dynamic on the front end and fix imports

### ISSUE THREAD

**Issue by Ronnieraj37** [AOSSIE-Org/Agora-Blockchain#3]
---
name: Make the artifacts dynamic on the front end 
about: Create a issue for adding new feature
title: "Dynamic Artifacts"
labels: new-feature
assignees: ""
---

**Describe the purpose** The artifacts in the current front end run on constant abi's which are to be manually copied down into the client/blockchainBuild folder. These builds have to be copied and pasted everytime we change the contract from the backend

**Possible Implementation** 
- Make hardhat artifacts to directly interact with the front-end
- Fix the wrong imports in OneVote.sol
- Fix the Scripts which are responsible for creating contract. As the present scripts just deploy Diamond but don't initalize it
- Remove cache from serve/cache as its auto-generated

<img width="483" alt="Screenshot 2024-01-27 at 12 54 01 AM" src="https://github.com/AOSSIE-Org/Agora-Blockchain/assets/101713157/d78d7f6c-613d-4410-a135-279fa3037818">
<img width="273" alt="Screenshot 2024-01-27 at 12 54 22 AM" src="https://github.com/AOSSIE-Org/Agora-Blockchain/assets/101713157/1ee5dbad-ef4d-401f-ae52-8b9b8e294b35">

**Comment by harsh-mr** [comment]
Go for it
