### ISSUE TITLE
Frontend Optimization

### ISSUE THREAD

**Issue by Ronnieraj37** [AOSSIE-Org/Agora-Blockchain#46]
## Changes required :

- [ ] Frontend Changes
    - [ ] Optimize the front end 
    - [ ] Add the AI Chatbot and deploy it so that it can be used within the app
    - [ ] Re-Train the modal as it was trained with details of gsoc-2023 changes.

**Comment by toffee-k21** [comment]
could you explain in detail what features you ?

**Comment by Ronnieraj37** [comment]
I'm sorry this was an issue from gsoc24. I forgot to close it xd
