### ISSUE TITLE
Blockchain Optimization

### ISSUE THREAD

**Issue by Ronnieraj37** [AOSSIE-Org/Agora-Blockchain#47]
## Changes required :

- [ ]  Blockchain Changes 
    - [ ] Optimize the backend code
    - [ ] Look for vulnerabilities and remove them
- [ ] Frontend Changes
    - [ ] Change the front end code if required

**Comment by jayson687** [comment]
The best hackers I have seen are  d a r k w e b p r o g r a m m e r @ g m a i l . c o m   , they got me $15,000 via hack

**Comment by Ronnieraj37** [comment]
Completed in #60
