### ISSUE TITLE
Feature Request: Redirect New Users Without Wallets to Ethereum Website

### ISSUE THREAD

**Issue by Tanya-ruby** [AOSSIE-Org/Agora-Blockchain#5]
As a new user without a wallet, I suggest we direct them to the official Ethereum website, which hosts a variety of wallets. This could be implemented by adding a 'I don't have a wallet' link on the registration page. This feature would enhance user experience and encourage more registrations.

[Link to the ethereum walletpage](https://ethereum.org/wallets/find-wallet)
<img width="617" alt="change" src="https://github.com/AOSSIE-Org/Agora-Blockchain/assets/157852043/77793435-d176-48ef-ae5a-055ef94dac06">

**Comment by abhisheksharma010** [comment]
Hello, can you assign this issue to me? I can easily resolve this.

**Comment by Tanya-ruby** [comment]
@harsh-mr waiting for your reply,if yes, ill link a pr !

**Comment by harsh-mr** [comment]
This is already covered, there is a prompt that leads you to metamask page if wallet is not installed check `onBoard.js`

**Comment by Tanya-ruby** [comment]
okay! i assumed users might use various wallets like coinbase and metamask

**Comment by harsh-mr** [comment]
Just providing link won't help, something like Wallet Connect needs to be integrated to support multiple wallets simultaneously , that is not integrated currently

**Comment by Tanya-ruby** [comment]
what do u think of rainbow-kit??it is very easy to implement and supports multiple wallets .They have a pre-made modal to connect as well .
<img width="404" alt="1" src="https://github.com/AOSSIE-Org/Agora-Blockchain/assets/157852043/a2054b1c-6945-41dc-a2b0-8ce14635f5da">
<img width="404" alt="2" src="https://github.com/AOSSIE-Org/Agora-Blockchain/assets/157852043/c4b50e8c-575d-4eff-9cb5-e6b9e00a818d">
<img width="404" alt="3" src="https://github.com/AOSSIE-Org/Agora-Blockchain/assets/157852043/81490e22-49a6-4b39-8c20-e9e65725bf6c">
