### ISSUE TITLE
Fix Typos: "Familarity" to "Familiarity," "Unneccessary" to "Unnecessary," and "Direcotry" to "Directory"

### ISSUE THREAD

**Issue by Arnavya** [AOSSIE-Org/Agora-Blockchain#56]
### Issue Description

This issue addresses multiple typos found in the documentation:

1. **"Familarity"** should be corrected to **"Familiarity."**
2. **"Unneccessary"** should be corrected to **"Unnecessary."**
3. **"Direcotry"** should be corrected to **"Directory."**

These corrections will improve the clarity and professionalism of the documentation. Please update the text accordingly to ensure accurate spelling throughout the project files.

### Screenshot
i) 
<img width="276" alt="Screenshot 2024-08-14 at 10 40 05 PM" src="https://github.com/user-attachments/assets/85396c56-e435-4e49-b721-029723665e91"> 

ii)
 <img width="328" alt="Screenshot 2024-08-14 at 10 40 49 PM" src="https://github.com/user-attachments/assets/cae0f90a-e18c-4fb4-bb11-c4351624a299">

iii)
<img width="344" alt="Screenshot 2024-08-14 at 10 42 20 PM" src="https://github.com/user-attachments/assets/e5fb19bf-f69b-4d52-95b0-8fd4d9f54bbb">

**Comment by Arnavya** [comment]
I would like to work on this @varunchitre15 @saisankargochhayat @heychirag @raghavpuri31

**Comment by sgnhyperion** [comment]
I would like to work on this issue @Arnavya

**Comment by sgnhyperion** [comment]
I have fixed this issued

**Comment by Arnavya** [comment]
I have already fixed the issue and raised PR for it.
