### ISSUE TITLE
Adding Particle Auth 

### ISSUE THREAD

**Issue by Ronnieraj37** [AOSSIE-Org/Agora-Blockchain#6]
---
title: Adding Particle Auth
about: Create a issue for adding new feature
labels: new-feature
assignees: ""
---

**Describe the purpose** - Currently the app only uses metamask to connect to web3 making it difficult for other walllet and web2 users to join the network.

**Possible Implementation** - 

- Adding Particle Auth which will let users to onboard in a much simple way allowing anyone to join the network and register on Agora Blockchain. 
- This also provides an option to buy tokens for gas fees using fiat currency. 

<img width="736" alt="Screenshot 2024-01-27 at 7 06 48 PM" src="https://github.com/AOSSIE-Org/Agora-Blockchain/assets/101713157/de415364-52c3-455f-8876-882192a7f5d0">

**Comment by harsh-mr** [comment]
Add more details for implementation, like what is required, I think you need to sign up to get started particle auth ?

So what are prerequisites?

**Comment by Ronnieraj37** [comment]
Yes we need to register the app through the particle auth page which will give us projectid , clientId , appId -> This provides Wallet as a service to users. We also need to register an app on wallet connect to give us access to all wallets which is the second part of the wallet. ( https://docs.particle.network/developers/auth-service/sdks/web ) After this we can add things like Supported Chains , etc.. When connected it'll trigger a function to get providers. One things that must be done is that we have to implement the providers globally to reduce creating more clutter in every page.
<img width="184" alt="Screenshot 2024-01-27 at 9 50 24 PM" src="https://github.com/AOSSIE-Org/Agora-Blockchain/assets/101713157/20e07d8b-fffd-465d-b4e2-e967366e605e">
<img width="303" alt="Screenshot 2024-01-27 at 9 50 30 PM" src="https://github.com/AOSSIE-Org/Agora-Blockchain/assets/101713157/e4c503a8-47c3-4f3f-ac0c-65ff5c63a73f">

**Comment by harsh-mr** [comment]
is it open-sourced or subscription-based?

**Comment by Ronnieraj37** [comment]
SDKs are open-source, but some of our more internal infrastructure is closed source, so they aren't completely open source but they're free-to-use and don't charge anything.
